name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run Tests
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: clean assemble publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}